### ISSUE TITLE
Predicates

### ISSUE THREAD

**Issue by SamTebbs33** [ash-lang/ash#19]
LinkedList<T> list = LinkedList<T>()
    func filter(Predicate<T> predicate) -> list.stream().filter(predicate)
    func forEach(Consumer<T> consumer) {
        list.stream().forEach(consumer)
    }
    func test() {
        var stream = filter(a -> a.toString().equals("hello"))
        forEach(a -> println(a))
    }

**Comment by Cyral** [comment]
IIRC the reason `.stream()` was used in Java was to keep it from interfering with existing APIs. I think it would be better if you went the C# route and made the methods like LINQ, where they operate directly on the collection (or any `IEnumerable`)

    list.filter(predicate)

**Comment by SamTebbs33** [comment]
@Cyral  I would like that, but in the above example, I'm using the java LinkedList class, so therefore I use the methods declared within the LinkedList class. One thing I would like to do is to create an alternative linked list implementation for Ash (perhaps one that extends LinkedList) which would have its own <code>filter()</code> function that would do exactly what you describe.

**Comment by SamTebbs33** [comment]
Closed in favour of #57
