### ISSUE TITLE
Use pre-existing functions as expressions

### ISSUE THREAD

**Issue by SamTebbs33** [ash-lang/ash#65]
```
func foo(a : int) -> int = a * 2

var bar = foo
// bar now points to foo and is of type "func (int) -> int"
bar(2) // It can be called just like any other variable that points to a function
```
This will mean that variables cannot have the same name as functions that are visible in the current scope (and vice versa).

**Comment by phase** [comment]
What about calling it with specified arguments?

```
func add(a : int, b : int) -> int = a + b

var subtract = foo(x, -y) //where `x` and `y` are variables to the function
subtract(1,2)
```

**Comment by SamTebbs33** [comment]
@phase That's an interesting suggestion, I would have to add some kind of syntactic feature so that your code above wouldn't be interpreted as a function call.

**Comment by phase** [comment]
Maybe instead of `var`, you could use `func`, and `->` instead of `=`:
```
func subtract -> add(x, -y)
```

**Comment by SamTebbs33** [comment]
@phase 
I guess that then you could just do this:
```
// A function that returns add(x, -y)
func subtract(x : int, y : int) -> int = add(x, -y)
```

**Comment by SamTebbs33** [comment]
This will be clunky, as it would require the generation of a new class for each pre-existing function used in this way, much like function objects.
