### ISSUE TITLE
instanceof switch/match statement

### ISSUE THREAD

**Issue by SamTebbs33** [ash-lang/ash#74]
There should be a construct that allows you to check if an object is an instance of any type.

```
switch_instance (obj) {
    String -> println("It's a String")
    Integer -> println("It's an Integer")
    _ -> println("It's something else")
}
```
The above code is equivalent to
```
if(obj instanceof String) println("It's a String")
else if(obj instanceof Integer) println("It's an Integer")
else println("It's something else")
```

Note that the keyword used is not at all decided upon.

Credit to @aranscope

**Comment by phase** [comment]
Maybe `match` as in [pattern matching](https://kerflyn.wordpress.com/2012/05/09/towards-pattern-matching-in-java/)?

**Comment by SamTebbs33** [comment]
@phase There is actually already a `match` statement in Ash, but this one would be specialised for checking if an object is an instance of any type, rather than if it matches a certain value.

**Comment by SamTebbs33** [comment]
This would seem to be a bit of an unnecessary change to the compiler as it could easily be done by the user.
